# Generated by Django 5.0.7 on 2024-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnname', models.CharField(max_length=50)),
                ('cncontact', models.IntegerField()),
                ('cnemail', models.CharField(max_length=50)),
                ('cnsub', models.CharField(max_length=50)),
                ('cnmsg', models.CharField(max_length=50)),
            ],
        ),
    ]
